version: 2.1
jobs:
  test-interpreter:
    docker:
      - image: node/node:16.18.0-alpine3.16
    steps:
      - checkout
      - run: cd interpreter
      - run: npm ci
      - run: make test

workflows:
  test:
    jobs:
      - test-interpreter

