version: 2.1

orbs:
  codecov: codecov/codecov@3.2.3

jobs:
  test-interpreter:
    docker:
      - image: node:16.18.0-alpine3.16
    steps:
      - checkout:
          path: ./interpreter
      - run:
          name: "Install system dependencies"
          command: apk add --update --no-cache --force-overwrite make curl gpg gpg-agent gpgv
      - run: 
          name: "Run tests"
          command: |
            npm ci
            make ci-test
       - codecov/upload

workflows:
  test:
    jobs:
      - test-interpreter

