version: 2.1
setup: true

orbs:
  path-filtering: circleci/path-filtering@0.1.3

parameters:
  interpreter-modified:
    type: boolean
    default: false


jobs:
  test-interpreter:
    docker:
      - image: node/node:16.18.0-alpine3.16
    steps:
      - checkout
      - run: cd interpreter
      - run: npm ci
      - run: make test

workflows:
  setup:
    jobs:
      - path-filtering/filter:
          base-revision: master
          mapping: |
            interpreter/.* interpreter-modified true
          config-path: .circleci/config.yml
  interpreter:
    when:
      or:
        - << pipeline.parameters.interpreter-modified >>
    jobs:
        - test-interpreter
