version: 2.1
jobs:
  test-interpreter:
    docker:
      - image: node:16.18.0-alpine3.16
    steps:
      - checkout
      - run: 
          name: "Run tests"
          command:
            cd interpreter
            npm ci
            make test

workflows:
  test:
    jobs:
      - test-interpreter

